### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by bzm121** [erictik/midjourney-api#100]
### the code that reproduces this issue or a replay of the bug

After upgrading to the latest version of midjourney@2.5.56, an error occurs when running.

### Describe the bug

**Describe the bug**

**Expected behavior**

**Screenshots**

### error log

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\bzm\AppData\Roaming\npm\node_modules\midjourney\node_modules\node-fetch\src\index.js from C:\Users\bzm\AppData\Roaming\npm\node_modules\midjourney\libs\midjourne.api.js not supported.
Instead change the require of index.js in C:\Users\bzm\AppData\Roaming\npm\node_modules\midjourney\libs\midjourne.api.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\bzm\AppData\Roaming\npm\node_modules\[4mmidjourney[24m\libs\midjourne.api.js:8:46)
    at Object.<anonymous> (C:\Users\bzm\AppData\Roaming\npm\node_modules\[4mmidjourney[24m\libs\midjourney.js:5:25)
    at Object.<anonymous> (C:\Users\bzm\AppData\Roaming\npm\node_modules\[4mmidjourney[24m\libs\index.js:4:22)
    at Object.<anonymous> [90m(C:\bzm\page\online\gpt\[39mmdj.js:1:22[90m)[39m {
  code: [32m'ERR_REQUIRE_ESM'[39m
}

Node.js v18.14.2

**Comment by bzm121** [comment]
Version 2.5.52 can be used normally.
Proxy support was added starting from version 2.5.55.

I used the undici library and made two code modifications to enable proxy support.

/midjourney/lib/midjourne.api.js

Declaration added:
```javascript
const {ProxyAgent, fetch} = require("undici")
//...
// when using fetch below
//...
let jD = {
method: "POST",
body: JSON.stringify(payload),
headers: headers,
}
if(this.config.Proxy){
jD.dispatcher = new ProxyAgent(this.config.Proxy);
}
const response = await fetch(`${this.config.DiscordBaseUrl}/api/v9/interactions`, jD);
```

/midjourney/lib/midjourney.message.js
Declaration added:
```javascript
const {ProxyAgent, fetch} = require("undici")
//...
// when using fetch below
//...
let jD = {
headers: headers
}
if(this.config.Proxy){
jD.dispatcher = new ProxyAgent(this.config.Proxy);
}
const response = await fetch(`${this.config.DiscordBaseUrl}/api/v10/channels/${this.config.ChannelId}/messages?limit=${limit}`, jD);
```

To use it, use:
```javascript
const client = new Midjourney({

    ServerId: process.env.ServerId,
    ChannelId: process.env.ChannelId,
    SalaiToken: process.env.SalaiToken,
    
    Debug: true,
    Ws:true,
    
    Proxy: "http://192.168.3.5:7890"
});
```

This enables successful use of proxy.
------------------------------------------------------------------------------------------
版本2.5.52 是可以正常使用的。
从2.5.55开始，加入了代理方式。

我使用了undici库，修改了两处代码，就可以成功使用代理了。

/midjourney/lib/midjourne.api.js

声明加入：
```javascript
const {ProxyAgent, fetch} = require("undici")
//...
//下面使用fetch时
//...
let jD = {
	method: "POST",
	body: JSON.stringify(payload),
	headers: headers,
}
if(this.config.Proxy){
	jD.dispatcher = new ProxyAgent(this.config.Proxy);
}
const response = await fetch(`${this.config.DiscordBaseUrl}/api/v9/interactions`, jD);
```

/midjourney/lib/midjourney.message.js
声明加入：
```javascript
const {ProxyAgent, fetch} = require("undici")
//...
//下面使用fetch时
//...
let jD = {
	headers: headers
}
if(this.config.Proxy){
	jD.dispatcher = new ProxyAgent(this.config.Proxy);
}
const response = await fetch(`${this.config.DiscordBaseUrl}/api/v10/channels/${this.config.ChannelId}/messages?limit=${limit}`, jD);
```

在调用时，使用：
```javascript
const client = new Midjourney({

    ServerId: process.env.ServerId,
    ChannelId: process.env.ChannelId,
    SalaiToken: process.env.SalaiToken,
    
    Debug: true,
    Ws:true,
    
    Proxy: "http://192.168.3.5:7890"
});
```

就能成功使用代理了。

**Comment by bzm121** [comment]
I don't know if I can modify the code. I'm not familiar with Github. I hope the author can see this and fix this feature.
--------------------------------------------------------
不知道我能不能修改代码？我对github确实不熟。希望作者看到，看能否修复这个功能。

**Comment by waitkafuka** [comment]
node-fetch不支持require导入，需要改为安装node-fetch@2。不知道作者能否修改下代码 @zcpua

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/commit/35b7030d2896d0d72b87b685cebf696cc19d392f

**Comment by bzm121** [comment]
Already solved.
