### ISSUE TITLE
Does anyone got blocked?

### ISSUE THREAD

**Issue by chenka** [erictik/midjourney-api#103]
### the code that reproduces this issue or a replay of the bug

I use it to generate a single image every 1 hour, 24 images per day.
Does anyone has an idea how to avoid from banning?
![image](https://github.com/erictik/midjourney-api/assets/837612/490459f4-7647-4328-aee1-a83a42a43bf2)

### Describe the bug

**Describe the bug**

**Expected behavior**

**Screenshots**

### error log

Got ban

**Comment by sequencerr** [comment]
what have you used? ws or message? just curious

**Comment by twesio** [comment]
By any chance, did you do it very periodically at predictable times, like

```
00:00:00
00:01:00
00:02:00
00:03:00
...
```

I bet this is easily detected. Try being more random, like a real user would be.

**Comment by chenka** [comment]
Yeap, I run it on predictable time, will change it.
Thank you for suggestion

---
Sarunyhot Suvannachoti (Kao)
สรัลยศ สุวรรณโชติ (เก้า)
095-941-6669

**Comment by chenka** [comment]
> what have you used? ws or message? just curious

message, `Ws:false`

**Comment by twesio** [comment]
@chenka Can you elaborate at what times you were running it, so that we know what not to do? 🙂

**Comment by chenka** [comment]
On the 1st day, I sequentially generate about 200++ images, but on days 2-8, I run it every 1 hour to generate 1 image at a time, last 10 executed it runs about XX:[00-10]:XX, [00-10] is minutes.
eg.
13:03:35
14:08:04
...

Maybe, I was suspicious on the 1st day.

---
Sarunyhot Suvannachoti (Kao)
สรัลยศ สุวรรณโชติ (เก้า)
095-941-6669

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/blob/main/.env.example#L5
https://github.com/erictik/midjourney-api/blob/main/example/imagine-ws.ts#LL15C1-L17C14

**Comment by zcpua** [comment]
#46

**Comment by lys623** [comment]
@chenka master, how to fix this issues? same issues

**Comment by chenka** [comment]
> @chenka master, how to fix this issues? same issues

I have been banned for 3 days. After that, I can use it properly.

**Comment by chenka** [comment]
I have been banned again.
![image](https://github.com/erictik/midjourney-client/assets/837612/6fb2c9ab-3824-4ef4-9da7-1c3b0c067f1d)
