### ISSUE TITLE
Fix Generating snowflake differs

### ISSUE THREAD

**Issue by sequencerr** [erictik/midjourney-api#108]
https://github.com/erictik/midjourney-api/blob/285469aaf455ceed120238ffec7b1fc32709184d/src/utls/index.ts#L10-L15

first of all, change it to Epoch.Discord
I checked and discord creates with workerId `0n`, proccessId `0n`, and sequence is starting from `0n` (also)

**Comment by zcpua** [comment]
DEFAULT_SEQUENCE is `0n`

**Comment by sequencerr** [comment]
> DEFAULT_SEQUENCE https://github.com/negezor/snowyflake/blob/master/src/constants.ts#L8 https://github.com/negezor/snowyflake/blob/master/src/snowyflake.ts#LL80C1-L82C37

ohh about this you are right, overlook, my mistake, sorry)
