### ISSUE TITLE
[FEAT] Closing WebSocket Connection

### ISSUE THREAD

**Issue by jakowenko** [erictik/midjourney-api#113]
Thank you for an amazing project.

**Is your feature request related to a problem? Please describe.**
I'd like to close the WebSocket connection after the image processing is complete. Right now it seems if this is called multiple times it will eventually hang.

**Describe the solution you'd like**
Either a `client.close()` method or exposing [wsClient](https://github.com/erictik/midjourney-api/blob/main/src/midjourney.ts#L13) so the consumer of this package can close the connection when they are done.

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/commit/7585c5b72de5d0a53e4330e5bacd07fc4e6a890c
