### ISSUE TITLE
The on/off switch for remix mode.

### ISSUE THREAD

**Issue by wrhsd1** [erictik/midjourney-api#133]
Thanks for your work.
When in remix mode, variations may encounter errors. Can you add an API that allows for the direct enablement or disablement of remix mode?

**Comment by lys623** [comment]
+1

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-client/blob/main/example/reset.ts

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/pull/169
https://github.com/erictik/midjourney-api/blob/main/example/prefer-remix.ts
