### ISSUE TITLE
client.Describe No result returned

### ISSUE THREAD

**Issue by lys623** [erictik/midjourney-api#136]
### the code that reproduces this issue or a replay of the bug

    const  imgUrl=`https://cdn.discordapp.com/attachments/1008571049039896576/1119473369813884958/manuelcorazzari_dirty_hands_holding_dirt_from_the_ground_sun_li_98bfb5e5-8c4f-4cb3-879a-bc229108e505.png`
    const msg = await client.Describe(imgUrl);
    console.log({ msg });

### Describe the bug

![image](https://github.com/erictik/midjourney-client/assets/4364314/d73dff27-281e-4d11-bb1c-4a948fd941ee)

No result returned

### error log

No result returned

**Comment by zcpua** [comment]
ws:true

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-client/blob/main/example/describe.ts

**Comment by clementepestelli** [comment]
I have the same problem with describe

### The Code
`    const msg = await client.Describe(
      "https://img.ohdat.io/midjourney-image/1b74cab8-70c9-474e-bfbb-093e9a3cfd5c/0_1.png"
    );
`
`    console.log({msg});`
### The output:
<img width="677" alt="image" src="https://github.com/erictik/midjourney-client/assets/11889500/e358785a-2db6-410f-a5e4-53c1a8b107e2">

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-client/blob/main/example/describe.ts#L18

**Comment by clementepestelli** [comment]
Yeah, I saw that client.Connect() but it gave me this error:
```
TypeError: client.Connect is not a function
    at main (/*******/index.js:12:18)
    at Object.<anonymous> (/*******/index.js:24:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```
Maybe I'm forgetting something important?

**Comment by zcpua** [comment]
npm install midjourney

**Comment by clementepestelli** [comment]
Ok, 
ny default npm installed v 2.7.79.
I forced the package.json to 3.0.80 and it works!
Thank you!

**Comment by lys623** [comment]
> Ok, ny default npm installed v 2.7.79. I forced the package.json to 3.0.80 and it works! Thank you!

![image](https://github.com/erictik/midjourney-client/assets/4364314/b9f28879-b2ad-4256-8b1e-83ba9089f98c)

Still no. What's wrong， "midjourney": "^3.0.81"

**Comment by lys623** [comment]
help @clementepestelli

**Comment by lys623** [comment]
![image](https://github.com/erictik/midjourney-client/assets/4364314/ebf7b06d-15ee-4785-b426-f50062952c4b)

The task was successfully created, but the returned result was not broadcast

![image](https://github.com/erictik/midjourney-client/assets/4364314/a14410f9-7e14-4dc6-a742-0f2f1b9997be)

**Comment by lys623** [comment]
有毒，仓库代码也不行，其他setting API，reset api都可以，就这个Describe 不行，救命

![image](https://github.com/erictik/midjourney-client/assets/4364314/ad3b359a-71d0-4153-9e4c-85e89400de4a)


![image](https://github.com/erictik/midjourney-client/assets/4364314/5b35bfe8-17a2-4675-b47f-f956295c3470)

**Comment by lx-0** [comment]
I have the same issue with the example. No msg is returned from Describe().

**Comment by lys623** [comment]
Find a solution where the bot gets a response when it is sent privately instead of in the server

**Comment by zcpua** [comment]
![20230704-120726](https://github.com/erictik/midjourney-api/assets/34678575/07de2792-5180-46f8-b21c-54d104e3b089)

**Comment by pyronaur** [comment]
Doesn't work for me either, using the latest version. Node 20, `midjourney@4.0.97`, no matter if I enable websockets or not - it submits the describe request and I can find the response in the discord channel, but MJ API never catches the response. Maybe because it's a public channel?
