### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by lys623** [erictik/midjourney-api#148]
### the code that reproduces this issue or a replay of the bug

TypeError: Cannot read properties of undefined (reading 'name')

### Describe the bug

![image](https://github.com/erictik/midjourney-client/assets/4364314/490140d9-8043-4a30-b9fe-8bb8c5ba7823)

### error log

👆

**Comment by zcpua** [comment]
thanks

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-client/commit/c6f2e865f6dcd7891b051bd67024452c39d11564
