### ISSUE TITLE
Add a website with Midjourney, Chat GPT-4, etc

### ISSUE THREAD

**Issue by cyb123-0** [erictik/midjourney-api#155]
I developed a web site to support Midjourney and Chat GPT - 4, you can put the website address ([www.91ai.pro](https://www.91ai.pro/)) making warehouse close to you? Thank you very much ~

<img width="1357" alt="image" src="https://github.com/erictik/midjourney-client/assets/135567159/4f7423af-5c44-42fc-a201-8fa28df6c497">

**Comment by lordmen99** [comment]
nice bro. have share the source code?

**Comment by oubotong** [comment]
Imagine packing up open-source API and selling it for money. LoL

**Comment by cyb123-0** [comment]
> nice bro. have share the source code?



> Is it open-source? Where are the source codes?

Thanks for the support. I am a Chinese developer, plan to open source, please look forward to ~
