### ISSUE TITLE
add zoomout feature

### ISSUE THREAD

**Issue by kenshincui** [erictik/midjourney-api#158]
The new version of midjourney adds the zoomout function, I hope to add this function

**Comment by oubotong** [comment]
Really need this feature

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-client/blob/main/example/zoomout.ts

**Comment by lx-0** [comment]
I have a 400 when calling the example. Other examples work.

<img width="1067" alt="image" src="https://github.com/erictik/midjourney-client/assets/51857173/03a7fcac-2e7c-454a-a8d3-83cd4d1b94ec">

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-client/blob/main/example/zoomout.ts

**Comment by zcpua** [comment]
> I have a 400 when calling the example. Other examples work.
> 
> <img alt="image" width="1067" src="https://user-images.githubusercontent.com/51857173/248559469-03a7fcac-2e7c-454a-a8d3-83cd4d1b94ec.png">

https://github.com/erictik/midjourney-client/commit/65ddf6a548a2001acb25b704ca1e579d97f19226#diff-c57c2cfe5739e8f09814483b7adbd919af529032ebafb0dbb2fdea8deabfbd3d

**Comment by kenshincui** [comment]
> https://github.com/erictik/midjourney-client/blob/main/example/zoomout.ts

I have successfully connected it and it works perfectly. I would like to ask if it is possible to add the "Make square" function.

**Comment by BownX** [comment]
The zoom out example works!  I would like to ask if there is any example of custom zoom out ?

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/pull/169

**Comment by zcpua** [comment]
> The zoom out example works! I would like to ask if there is any example of custom zoom out ?

https://github.com/erictik/midjourney-api/blob/main/example/customzoom.ts
