### ISSUE TITLE
Supporting Remix v5.2

### ISSUE THREAD

**Issue by vanheerdena** [erictik/midjourney-api#162]
**Is your feature request related to a problem? Please describe.**
I am trying to create consistent images for a story book. MJ 5,2 finally makes this possible through the remix mode. I'm frustrated when I try use Remix on in Variations and it doesn't work.

**Describe the solution you'd like**
Allowing an endpoint for remix with the ability to adjust the remix prompt would be amazing.

**Describe alternatives you've considered**
Without images consistency I am a bit stumped using this code.

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/pull/169
