### ISSUE TITLE
CustomApi failed with status 404' 'Error: CustomApi failed with status 404

### ISSUE THREAD

**Issue by ACE-jianyue** [erictik/midjourney-api#174]
### the code that reproduces this issue or a replay of the bug

![image](https://github.com/erictik/midjourney-api/assets/48401885/a76b86d6-0223-41c1-a442-684ee03622c2)

### Describe the bug

**Describe the bug**

**Expected behavior**

**Screenshots**

### error log

![image](https://github.com/erictik/midjourney-api/assets/48401885/6b09bc3c-e21a-43a5-a58e-b8d4c4fa3368)

**Comment by zcpua** [comment]
``` bash 
git clone https://github.com/erictik/midjourney-api.git
cd midjourney-api
npx tsx example/upscale-ws.ts 
```
https://github.com/erictik/midjourney-api/blob/main/example/upscale-ws.ts

if it work , maybe your code wrong
