### ISSUE TITLE
使用Upscale选择了某一张图以后，如果进一步选择

### ISSUE THREAD

**Issue by xiaoqixiaoqi1113** [erictik/midjourney-api#184]
![image](https://github.com/erictik/midjourney-api/assets/107258825/6a63c311-712e-44ca-ad6f-39bf13be3910)
有什么方法可以选择这两个选项吗

**Comment by zcpua** [comment]
#158  same issue

**Comment by xiaoqixiaoqi1113** [comment]
> #158 same issue

I didn't find information about the Vary(Strong) and Vary(Subtle) options

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/blob/main/example/customzoom.ts#L48C1-L62C6
```
Upscale?.options?.find((o) => o.label === "Vary(Strong)");
 const Vary = await client.Custom({
    msgId: <string>Upscale.id,
    flags: Upscale.flags,
    content: `prompt,
    customId: zoomout.custom,
    loading: (uri: string, progress: string) => {
      console.log("loading", uri, "progress", progress);
    },
  });
```

**Comment by xiaoqixiaoqi1113** [comment]
> https://github.com/erictik/midjourney-api/blob/main/example/customzoom.ts#L48C1-L62C6
> 
> ```
> const vary = Upscale?.options?.find((o) => o.label === "Vary(Strong)");
>  const msg = await client.Custom({
>     msgId: <string>Upscale.id,
>     flags: Upscale.flags,
>     content: `prompt,
>     customId: vary.custom,
>     loading: (uri: string, progress: string) => {
>       console.log("loading", uri, "progress", progress);
>     },
>   });
> ```

Can I use all of the above options in this way Including Zoom Out...

**Comment by zcpua** [comment]
Of course it's okay.
U and V are also ok.

**Comment by xiaoqixiaoqi1113** [comment]
> Of course it's okay. U and V are also ok.



> Of course it's okay. U and V are also ok.

But I see that the option (custom Zoom) seems to be setting the content to "xxx -- Zoom xx". Is this a mandatory setting? And (Zoom Out) do you want to configure the level to 2X or 1.5X?

**Comment by zcpua** [comment]
same as MidJourney

**Comment by xiaoqixiaoqi1113** [comment]
> same as MidJourney

I see what you mean, I will try to use it now, thank you for your answer
