### ISSUE TITLE
Is there a possibility to select one of the "first shots"

### ISSUE THREAD

**Issue by jubak01** [erictik/midjourney-api#2]
Hey Eric !

First Thanks for your amazing work, it works great on my side :)

Are you planning to have a solution to be able to select one of the 4 options, then retreive the uri ?

Or even to make variation/refresh just like on discord :)

Have a great day

**Comment by zcpua** [comment]
Hi Jubak
You can refer to
https://github.com/erictik/midjourney-api/blob/main/example/upscale.ts

I don't know if it's what you want

**Comment by jubak01** [comment]
Oh ok ! I went too fast through the project you actually already worked on it, great thx mate !
