### ISSUE TITLE
How to set VersionSelector with API?

### ISSUE THREAD

**Issue by zongzi531** [erictik/midjourney-api#264]
How to set `'MJ::Settings::VersionSelector'` with API

I want to set model, anyone know how set it.

**Comment by zcpua** [comment]
example/settings.ts

**Comment by zongzi531** [comment]
> example/settings.ts

I try run this code
```typescript
const msg = await client.Settings()

console.log(msg.options)
// [
//   {
//     type: 3,
//     style: undefined,
//     label: undefined,
//     custom: 'MJ::Settings::VersionSelector'
//   },
// ]
```

I can't see like `niji5` or another model, and I don't know default model customId. so bad...

**Comment by Slushbanq** [comment]
just add a drop down menu with values of 5, 5.1, 5.2 and 6. At the end of the prompt add "--v"*yourversionvalue* and you'll be fine. You have to have a default value for the version otherwise it will keep on giving invalid parameter error.

**Comment by zongzi531** [comment]
> just add a drop down menu with values of 5, 5.1, 5.2 and 6. At the end of the prompt add "--v"_yourversionvalue_ and you'll be fine. You have to have a default value for the version otherwise it will keep on giving invalid parameter error.

@Slushbanq Thanks, this way probably the only method that works at the moment.
