### ISSUE TITLE
Does this project working?

### ISSUE THREAD

**Issue by tal412** [erictik/midjourney-api#31]
I keep getting this error:

![image](https://github.com/erictik/midjourney-api/assets/36299714/8cda490f-bbdc-4d15-8da8-4d416d6cfbe1)

**Comment by Hafagonia** [comment]
Same here, did you fix it ?

**Comment by lordmen99** [comment]
> Same here, did you fix it ?

if u want setup or wany mj api. i have already develop it. add my telegram @Newcoinmod1

**Comment by zcpua** [comment]
Setup SESSION_ID try it

**Comment by iamkunal9** [comment]
your auth token is invalid kindly check them its working fine for me tho...
