### ISSUE TITLE
If there is a queuing situation, an error will be reported

### ISSUE THREAD

**Issue by nightwhite** [erictik/midjourney-api#33]
Looks like it is over time

**Comment by hejuntt1014** [comment]
是否能详细描述你的场景,我这边做了一定的修改,可能有你需要的解决方案

**Comment by nightwhite** [comment]
我看到了 新增了一个查询最新历史消息的功能，不过是否可以在创建 imagine 马上获取 id呢

**Comment by nightwhite** [comment]
> 

就是目前会有一个问题，如果出现请求超时会报错。因为排队的问题。

**Comment by nightwhite** [comment]
> 是否能详细描述你的场景,我这边做了一定的修改,可能有你需要的解决方案

limit the number of concurrent interactions

**Comment by hejuntt1014** [comment]
请求出图的速度是midjourney决定的,跟api无关,如果,这个项目默认是请求200秒左右,建议你开着discord网页版观察是否是200秒discord还没出图,如果在超时前已经出图,有报错,建议贴出报错的信息

**Comment by nightwhite** [comment]
> 



> 请求出图的速度是midjourney决定的,跟api无关,如果,这个项目默认是请求200秒左右,建议你开着discord网页版观察是否是200秒discord还没出图,如果在超时前已经出图,有报错,建议贴出报错的信息

用别的方案解决了，新增了一个查历史记录的方法，用那个去解决了
