### ISSUE TITLE
variation invalid

### ISSUE THREAD

**Issue by nightwhite** [erictik/midjourney-api#34]
![image](https://github.com/erictik/midjourney-api/assets/22722256/616af7c2-1231-48cc-b55f-78e38ce3853a)

According to the example code, after the execution is completed, V2 will not generate pictures

**Comment by zcpua** [comment]
![20230515-120626](https://github.com/erictik/midjourney-api/assets/34678575/27092aae-8be9-4d8f-94a9-94ec8f080232)

**Comment by zcpua** [comment]
maybe you have enabled blend mode

**Comment by nightwhite** [comment]
Yes, my old configuration is changed to you as if you

![image](https://github.com/erictik/midjourney-api/assets/22722256/9dc42862-4497-415f-9445-332dd415420e)
