### ISSUE TITLE
cannot find ../libs

### ISSUE THREAD

**Issue by pekatBart** [erictik/midjourney-api#36]
Hi, I have quite a problem to make this work. Could you please help me a little bit?

1) Made a clone of https://github.com/erictik/midjourney-api
2) setup all env variables (hopefully correct) and installed via command "yarn" in a root of the repo
3) Then I tried run node example with a command "node example/imagine.js".

Error: Cannot find module '../libs'

**Comment by zcpua** [comment]
Hey , u need run yarn build
