### ISSUE TITLE
Can I call back the error message when the prompt word is wrong?

### ISSUE THREAD

**Issue by Monsterespin** [erictik/midjourney-api#38]
Can I call back the incorrect card information when the prompt word is wrong or not conforming to the specification? Thanks

**Comment by zcpua** [comment]
No, I can't get  the wrong message
![5292e285-d966-4412-b70c-32a06699cfaf](https://github.com/erictik/midjourney-api/assets/34678575/181e630f-45fb-45d1-be15-bbee3b95c93b)

**Comment by zcpua** [comment]
u can try v2.2

**Comment by yklingaOa** [comment]
https://github.com/erictik/midjourney-ui 的最新版本暂时还无法支持 v2.2吧？
