### ISSUE TITLE
Improvement idea

### ISSUE THREAD

**Issue by jubak01** [erictik/midjourney-api#40]
It would be nice to increase the delay for the returned {msg}, sometimes Midjourney can take time to start the generation, and msg is returned undefined before the generation ended.

I'm thinking about doing it manually meanwhile, can you help me by giving me the line of code (if possible) my knowledge are limited ?

Thank you

**Comment by zcpua** [comment]
```
const msg = await client.Imagine("A little pink elephant", (uri: string) => {
  console.log("loading", uri);
});
```
