### ISSUE TITLE
'no message found' error

### ISSUE THREAD

**Issue by MishaMgla** [erictik/midjourney-api#45]
Quite often no message found after awaiting imagine execution.
Idk on what variables it happens, it looks like it just randomly appears time to times. 
Switching to new created clean channel helps for a while.

<img width="354" alt="image" src="https://github.com/erictik/midjourney-api/assets/98478673/8a182c4e-c899-4bd8-855a-247faf1b92cb">

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/blob/main/example/imagine-ws.ts

**Comment by MishaMgla** [comment]
Ty! I missed client.init() before starting image generations
