### ISSUE TITLE
mj好像上线了流控，有解决方案吗？

### ISSUE THREAD

**Issue by lys623** [erictik/midjourney-api#46]
![image](https://github.com/erictik/midjourney-api/assets/4364314/17231941-80ba-4ef2-a197-833779630f2f)

**Comment by zcpua** [comment]
This project is for learning and personal use. It is not suitable for commercial use.

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/commit/59393c382cc0744900e5d2251bda91e2dc3481ed
