### ISSUE TITLE
midjourney-ui: build and running failed

### ISSUE THREAD

**Issue by saccura** [erictik/midjourney-api#47]
Any request in dev mode fires this error

**Running on Ubuntu 20:**
`error - node:child_process
Module build failed: UnhandledSchemeError: Reading from "node:child_process" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:child_process
./node_modules/discord.js/src/sharding/Shard.js
./node_modules/discord.js/src/index.js
./node_modules/midjourney/libs/midjourney.js
./node_modules/midjourney/libs/index.js
wait  - compiling /_error (client and server)...
warn  - ./node_modules/discord.js/src/client/websocket/WebSocketManager.js
Module not found: Can't resolve 'zlib-sync' in '/home/anton/_npm_projects/midjourney-ui/node_modules/discord.js/src/client/websocket'

Import trace for requested module:
./node_modules/discord.js/src/client/websocket/WebSocketManager.js
./node_modules/discord.js/src/index.js
./node_modules/midjourney/libs/midjourney.js
./node_modules/midjourney/libs/index.js
`

**Running on Windows 10:**
`
- error node:child_process
Module build failed: UnhandledSchemeError: Reading from "node:child_process" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:child_process
./node_modules/discord.js/src/sharding/Shard.js
./node_modules/discord.js/src/index.js
./node_modules/midjourney/libs/midjourney.js
./node_modules/midjourney/libs/index.js`

Trying to build also failed. Please assist

**Comment by zcpua** [comment]
"midjourney": "^2.1.30", or "midjourney": "^2.2.33"
