### ISSUE TITLE
await Imagine not catching completed image

### ISSUE THREAD

**Issue by MishaMgla** [erictik/midjourney-api#49]
Calling await imagine() hangs on progress 93% and doesn`t return completed generation png image.

<img width="467" alt="image" src="https://github.com/erictik/midjourney-api/assets/98478673/5091e1c1-6ae4-49a2-a5eb-4e2e7c99c756">

![image](https://github.com/erictik/midjourney-api/assets/98478673/521b5a72-aba3-436f-9afe-ea0c03611676)

**Comment by zcpua** [comment]
have logs？

**Comment by MishaMgla** [comment]
> Has the system generated any error logs recently?

Nope, it even does not fail by timeout.
Attached forgotten logs from console.

**Comment by zcpua** [comment]
![image](https://github.com/erictik/midjourney-api/assets/34678575/d1dbe8bd-b5e4-4d1a-b969-380bafa2aa0f)

**Comment by MishaMgla** [comment]
> So it seems the success event is happening but not triggering the response back from the function. Is this correct?

Exactly

**Comment by zcpua** [comment]
> So it seems the success event is happening but not triggering the response back from the function. Is this correct?

![20230527-134419](https://github.com/erictik/midjourney-api/assets/34678575/a36c6278-902a-4726-9545-b1632d214486)

**Comment by MishaMgla** [comment]
> I am seeing this behavior when testing with longer prompts (750 characters) but not with shorter ones... 50 characters...

I digged little bit, but not sure : do trigger checking attachment file extension only?

**Comment by MishaMgla** [comment]
> It could be related to this: https://www.reddit.com/r/midjourney/comments/13k7vqa/starting_today_original_message_was_deleted/

Curious. I faced this behaviour previously, but not often, did not pay attention, when it happens I just restarted my app. Could it be something like that my account marked as suspiocious and moderated more strictly, as I generated pretty much images, sometimea I need to verify that I am not a bot.

**Comment by wanglong167** [comment]
触发审核的可能会被 没有完成事件
 
丹方 
@zcpua 

Create a poster for a city rooftop party, night, sexy, cyberpunk

![image](https://github.com/erictik/midjourney-api/assets/456516/909576a8-804c-49c6-a4e9-4dbbe0aa3b3e)
<img width="1130"   src="https://github.com/erictik/midjourney-api/assets/456516/865b81f1-6404-413d-bebb-b9861a274442">

```
 //done image 
    const progress = content?false: content.match(/ \(([0-9]+)%\)$/);

    if (!nonce && (!application_id||!progress)) {
      this.log("done image");
      this.done(message);
      return;
    }
```

**Comment by zcpua** [comment]
#101

**Comment by artemptushkin** [comment]
@zcpua what's the solution to 404 due to deleted messages (as I understood by moderation mechanisms)?
