### ISSUE TITLE
Upscale no msg return

### ISSUE THREAD

**Issue by ninvfeng** [erictik/midjourney-api#5]
Upscale no msg return. when the Upscale img has been created, but the msg2 not return, still repect waitting
cmd: npx tsx example/upscale.ts

**Comment by MishaMgla** [comment]
Same issue

**Comment by jubak01** [comment]
+1 Same issue

**Comment by onarbf** [comment]
+1 same issue

**Comment by zsh2401** [comment]
+1 Same issue, and Variation's loading callback is not working.

**Comment by hejuntt1014** [comment]
Change the code on line 162 of the file midjourney.ts from 
`return await this.WaitOptionMessage(content, `Upscaled`, loading);`
 to 
`return await this.WaitOptionMessage(content, `Image #${index}`, loading);`

**Comment by hejuntt1014** [comment]
Change the code on line 162 of the file midjourney.ts from
`return await this.WaitOptionMessage(content,\ `Upscaled\`, loading);`
to
`return await this.WaitOptionMessage(content, \`Image #${index}\`, loading);`

**Comment by hejuntt1014** [comment]
Change the code on line 162 of the file midjourney.ts from
return await this.WaitOptionMessage(content, Upscaled, loading);
to
return await this.WaitOptionMessage(content, Image #${index}, loading);

**Comment by tizzle** [comment]
> and Variation's loading callback is not working.

This is still not addressed, is it?
