### ISSUE TITLE
ReadMe correction

### ISSUE THREAD

**Issue by Bagiadrums** [erictik/midjourney-api#54]
I love your Project!

A little Correction for the readme:
"
Then, run the example with the following command:

npx tsx example/imagine-ws.ts
npx tsx example/upscale-w.ts
"

should be :
"
Then, run the example with the following command:

npx tsx example/imagine-ws.ts
npx tsx example/upscale-ws.ts
"

Have a great day.

**Comment by zcpua** [comment]
thanks
