### ISSUE TITLE
Bug report, The callback failed when the service was restarted. P0 Priority, thanks.

### ISSUE THREAD

**Issue by lys623** [erictik/midjourney-api#61]
![image](https://github.com/erictik/midjourney-api/assets/4364314/4e1ef450-2a35-4deb-a50d-ac8356e53719)

Can you redesign the interaction flow? For example, a new task will return an id, and mj will return the id information after generating the picture

**Comment by zcpua** [comment]
Service restart causes http to close

**Comment by lys623** [comment]
> Service restart causes http to close

Is there a solution? Because when the ws link reconnects, it returns a result
