### ISSUE TITLE
Small Variation issue

### ISSUE THREAD

**Issue by jubak01** [erictik/midjourney-api#62]
Hey again,

thx for ur great work !

I've noticed that if you variate a generation twice, seems like the code cannot make the difference between the first variation and the second one, so it takes the first one instead of waiting for the second one.

**Comment by jubak01** [comment]
Maybe the code could check the first date/hour of the last message that look like the right anwser before choosing it as the right msg.

The rule could work cause it is not possible to start receiving an answer before the request has been sent ^^

**Comment by varnew** [comment]
> Hey again,
> 
> thx for ur great work !
> 
> I've noticed that if you variate a generation twice, seems like the code cannot make the difference between the first variation and the second one, so it takes the first one instead of waiting for the second one.

please show the code.
