### ISSUE TITLE
zlib error

### ISSUE THREAD

**Issue by hd996** [erictik/midjourney-api#67]
if (data.length >= 4 && data.readUInt32BE(data.length - 4) === 0x0ffff) {
        this.inflate.flush(
          ZlibConstants.Z_SYNC_FLUSH,
          this.handleFlushComplete.bind(this),
        )
      }
Sometimes an error occurs when executing the above statement

Uncaught Exception thrown Error: invalid stored block lengths
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}

**Comment by zcpua** [comment]
#69
