### ISSUE TITLE
What value for serverId?

### ISSUE THREAD

**Issue by LukeFerris** [erictik/midjourney-api#73]
My understanding of Discord is that direct messages (of the type we are having with the MidJourney Bot) don't exist on a specific server. Likewise accounts don't exist on a specific server.

I'm getting error 400 and I suspect it's because I'm not putting in the right serverId. Where do I get it?

Thanks for any help!

**Comment by zcpua** [comment]
![image](https://github.com/erictik/midjourney-api/assets/34678575/e66a5ade-bdda-4d88-92f3-94f4d7ab7ab7)

**Comment by LukeFerris** [comment]
Legend.. thanks.

**Comment by LukeFerris** [comment]
And so.. if it's a DM then the server id is "@me"?

**Comment by LukeFerris** [comment]
Just as an update. That doesn't seem to work (I still get the 400). It does work however if I use one of the newbie channels and corresponding server. My guess then is the intention here is to use that. Am I right?

**Comment by zcpua** [comment]
DM not supported.

**Comment by LukeFerris** [comment]
Thanks for the confirmation. All working well with that info.
