### ISSUE TITLE
Feature asking：support /describe?

### ISSUE THREAD

**Issue by lys623** [erictik/midjourney-api#78]
expect input image url: 

https://cdn.discordapp.com/attachments/1109094135593439282/1114235922507104356/20230603-005529.jpeg

expect output 4 prompt：

1️⃣ an illustration of a little girl with a halo in the background, in the style of light yellow and red, minimalist cartooning, angelic photograph, cartoonish characters, animated gifs, close-up, bold, cartoonish lithographs --ar 58:77

2️⃣ a child in red and black with an angel halo, in the style of [tom whalen](https://goo.gl/search?artist%20tom%20whalen), blink-and-you-miss-it detail, emotional portraiture, [dan matutina](https://goo.gl/search?artist%20dan%20matutina), light yellow and white, [rosalba carriera](https://goo.gl/search?artist%20rosalba%20carriera), playful character designs --ar 58:77

3️⃣ a girl wearing angel halo and looking, in the style of [tom whalen](https://goo.gl/search?artist%20tom%20whalen), close-up, red, [robert munsch](https://goo.gl/search?artist%20robert%20munsch), playful cartoons, [nicolaes maes](https://goo.gl/search?artist%20nicolaes%20maes), somber mood --ar 58:77

4️⃣ 'death to angels' by zhengyoo j sung, in the style of flat illustrations, light red and light gold, kidcore, close-up, playful expressions, commission for, emphasis on negative space --ar 58:77

**Comment by kenshincui** [comment]
+1

**Comment by BlueSchnabeltier** [comment]
+1

**Comment by zcpua** [comment]
#112
