### ISSUE TITLE
/info这个命令,怎么才能拿到数据返回了

### ISSUE THREAD

**Issue by xhzth70911** [erictik/midjourney-api#88]
### the code that reproduces this issue or a replay of the bug

![1685936109554](https://github.com/erictik/midjourney-api/assets/24982706/d295b57f-15b5-4917-a06e-eedc6ff1f7c0)
我复制了/info的的请求的json, 为什么protected async safeIteractions，返回204的的status，没有其他的返回了,如何才能像VariationApi有正确的内容返回了？  拿到/info的返回，谢谢
Job Mode: Fast
Visibility Mode: Public
Fast Time Remaining: 9.24/15.0 hours (61.59%)
Lifetime Usage: 2248 images (34.50 hours)
Relaxed Usage: 464 images (7.30 hours)

### Describe the bug

/info

### error log

/info

**Comment by zcpua** [comment]
#91

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/blob/main/example/imagine-info.ts

**Comment by lys623** [comment]
话说这个api的使用场景是什么？

**Comment by xhzth70911** [comment]
> https://github.com/erictik/midjourney-api/blob/main/example/imagine-info.ts
我下载了你最新代码midjourney-api-main   
我运行 imagine-info.ts  我设置了SalaiToken  报错Error: ImagineApi failed with status 400，
但是我用同一个SalaiToken  去运行imagine.ts  可以正常生成图片
