### ISSUE TITLE
why does the socket disconnect every few minutes

### ISSUE THREAD

**Issue by ywachao** [erictik/midjourney-api#96]
### the code that reproduces this issue or a replay of the bug

why does the socket disconnect every few minutes

### Describe the bug

**Describe the bug**

**Expected behavior**

**Screenshots**

### error log

open 0 2023-06-07T16:42:17.807Z
onclose  1006 2023-06-07T16:43:47.339Z
open 1 2023-06-07T16:43:47.966Z
onclose  1006 2023-06-07T16:45:17.620Z
open 2 2023-06-07T16:45:18.252Z
onclose  1006 2023-06-07T16:46:48.037Z
open 3 2023-06-07T16:46:48.843Z
onclose  1006 2023-06-07T16:48:18.348Z
open 4 2023-06-07T16:48:19.208Z
onclose  1006 2023-06-07T16:49:48.630Z
open 5 2023-06-07T16:49:49.267Z
onclose  1006 2023-06-07T16:53:18.965Z
open 6 2023-06-07T16:53:19.583Z
onclose  1006 2023-06-07T16:54:49.296Z
open 7 2023-06-07T16:54:49.965Z
onclose  1006 2023-06-07T16:56:20.319Z
open 8 2023-06-07T16:56:20.967Z
onclose  1006 2023-06-07T16:57:50.614Z
open 9 2023-06-07T16:57:51.282Z
onclose  1006 2023-06-07T16:59:21.015Z
open 10 2023-06-07T16:59:21.709Z
onclose  1006 2023-06-07T17:02:51.337Z
open 11 2023-06-07T17:02:52.040Z

**Comment by zcpua** [comment]
#95
