### ISSUE TITLE
点v的时候，永远只会返回同一张图片

### ISSUE THREAD

**Issue by waitkafuka** [erictik/midjourney-api#97]
### the code that reproduces this issue or a replay of the bug

如题。不管点v1还是v2，出来的图片都一样。定位了一下，是以下代码的问题：
<img width="915" alt="image" src="https://github.com/erictik/midjourney-api/assets/8555018/0171973f-543d-410e-aa8b-f2a3321349bf">
这里z字符串匹配的时候，这一次的 V 和上一次的 V 没有考虑时间先后，导致每次都返回的上一次的结果。
这个问题不知道现在改过了吗？上面截图是我自己改了一下源代码之后的。

### Describe the bug

**Describe the bug**

**Expected behavior**

**Screenshots**

### error log

多次V 返回的结果一样。

**Comment by sukbearsuwu** [comment]
而且loading回调函数也有问题，我打印不出来progress

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/blob/main/example/variation-ws.ts

**Comment by sukbearai** [comment]
> https://github.com/erictik/midjourney-api/blob/main/example/variation-ws.ts

我在云函数中使用，无法使用ws，只能通过轮询来获取，然后就有问题。

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/commit/d5369f92f1b741d88e9fa12af234df490e6f149d

**Comment by zcpua** [comment]
same issue #70
